### ISSUE TITLE
Create methods for Epic endpoints

### ISSUE THREAD

**Issue by allardbrain** [allardbrain/clubhouse-client#7]
Create a method in the `ClubhouseClient` class in `api.py` for [each of the Epic endpoints](https://clubhouse.io/api/rest/v3/#Epics) offered by the Clubhouse API.

**Those are:**
- [x] `list_epics`
- [x] `create_epic`
- [x] `get_epic`
- [x] `update_epic`
- [x] `delete_epic`
- [x] `list_epic_comments`
- [x] `create_epic_comment`
- [x] `get_epic_comment`
- [x] `create_epic_comment_comment`
- [x] `update_epic_comment`
- [x] `delete_epic_comment`
- [x] `list_epic_stories`

Use the formatting of the Milestone-related methods in the `ClubhouseClient` class as a guide.

**Comment by allardbrain** [comment]
Closed by #15
